apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-demo
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-demo
  template:
    metadata:
      labels:
        app: django-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: django-demo
        image: devsecops-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
