apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-monitoring-servicemonitor-rb
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-monitoring-servicemonitor-role
  apiGroup: rbac.authorization.k8s.io
