apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-monitoring-servicemonitor-role
  namespace: monitoring
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get","list","watch","create","update","patch","delete"]
