apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-demo-sm
  namespace: monitoring
  labels:
    release: mon
spec:
  namespaceSelector:
    matchNames:
      - devsecops
  selector:
    matchLabels:
      app: django-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
